name: Clear Repository

on:
  schedule:
    - cron: '0 16 * * *'  # UTC时间16点对应UTC+8的0点
  workflow_dispatch: 
    
jobs:
  clear-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许推送更改
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # 不使用默认的 GITHUB_TOKEN

    - name: Delete files and directories
      run: |
        # 删除除 .git 和 .github 外的所有内容
        find . -mindepth 1 -maxdepth 1 -not \( -name ".git" -o -name ".github" \) -exec rm -rf {} +

    - name: Commit and push changes
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |
        git config --global user.email "yangrenruiyrr@163.com"
        git config --global user.name "杨人瑞"
        git add .
        
        # 检查是否有变更需要提交
        if [ -n "$(git status --porcelain)" ]; then
          echo "$(date '+%Y-%m-%d %H:%M:%S')">update_time
          git commit -m "每日清空仓库（UTC+8 零点）"
          git push https://${PERSONAL_ACCESS_TOKEN}@github.com/${{ github.repository }}.git
        else
          echo "无变更可提交。"
        fi    
